## SECTION: Math prerequisites
### LECTURE: Matrix multiplication

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.15 -0.14 -0.77 -0.07 -0.39]
 [ 1.32 -1.69 -0.74 -1.04 -3.45]
 [-0.22  0.27  1.16 -0.49 -0.12]]
 
[[ 0.86  1.28 -0.2   0.46]
 [-2.26 -3.68 -1.63 -0.85]
 [-0.06 -0.16  0.9  -0.21]
 [-0.03 -0.15 -0.07 -0.01]
 [-0.28  0.86 -0.04  0.02]
 [-1.22 -2.25 -0.61 -0.54]
 [-1.36 -1.73 -1.09 -0.43]]


# Using pytorch

In [4]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-0.5000,  1.2400,  0.3600, -0.6100, -0.5300, -0.5200, -0.8600],
        [-0.1300, -0.0800,  0.6900,  1.0700,  0.3500, -0.6500,  0.0800],
        [-2.2800,  0.0500,  0.8200,  1.2100, -0.5800,  0.0200,  0.6700]],
       dtype=torch.float64)
 
tensor([[-0.5000,  1.2400,  0.3600, -0.6100, -0.5300, -0.5200, -0.8600],
        [-0.1300, -0.0800,  0.6900,  1.0700,  0.3500, -0.6500,  0.0800],
        [-2.2800,  0.0500,  0.8200,  1.2100, -0.5800,  0.0200,  0.6700]])
